### ISSUE TITLE
CSS3实现全景图特效

### ISSUE THREAD

**Issue by ansenhuang** [ansenhuang/ansenhuang.github.io#4]
本篇文章将给大家带来一个css3的黑科技：如何仅仅使用css来实现全景图的效果？

最终效果演示：[demo](https://ansenhuang.github.io/example/css/panorama-photo.html)
## 页面布局

``` html
<div class="panorama"></div>
```
## 基础样式

首先定义一些基本的样式和动画

``` css
.panorama {
  width: 300px;
  height: 300px;
  background-image: url(http://7vilbi.com1.z0.glb.clouddn.com/blog/6608185829213862083.jpg);
  background-size: auto 100%;
  cursor: pointer;
  animation: panorama 10s linear infinite alternate;
}

@keyframes panorama {
  to {
    background-position: 100% 0;
  }
}
```

`background-size: auto 100%;` 这段代码的意思是让图片的高等于容器的高，并且水平方向自动，即图片最左边贴着容器左侧。

执行动画的流程是：周而复始、往复交替、线性并且时间周期是10s。
## 手动控制动画执行

到这里为止，当我们打开该网页后，立马会出现一张图片来回水平滑动的效果。但是这样的话，访客可能会被动画吸引而忽略了真正的内容。
我们的要求是当鼠标悬浮于图片时才让它动起来，我们当然可以很简单的实现这个效果。

删除之前的`animation`，添加以下样式。

``` css
.panorama:hover,
.panorama:focus {
  animation: panorama 10s linear infinite alternate;
}
```

现在的效果是：鼠标移入图片，图片开始水平来回滑动。
## 动画的优化

虽然效果达到了，但是你会发现，当鼠标移出图片，图片立刻回到初始位置。
对于我们来说，这有点突然，如何记录图片当前的位置并且当鼠标移入时继续执行动画呢？

我们可以依靠这个属性`animation-play-state: paused | running`，它表示动画的两个状态：暂停和运行。
## 完整css代码

``` css
.panorama {
  width: 300px;
  height: 300px;
  background-image: url(http://7vilbi.com1.z0.glb.clouddn.com/blog/6608185829213862083.jpg);
  background-size: auto 100%;
  cursor: pointer;
  animation: panorama 10s linear infinite alternate;
  animation-play-state: paused;
}

.panorama:hover,
.panorama:focus {
  animation-play-state: running;
}

@keyframes panorama {
  to {
    background-position: 100% 0;
  }
}
```
